#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    remove|deconfigure)
        deb-systemd-invoke disable memlinkd.service >/dev/null 2>&1 || true
        deb-systemd-invoke stop memlinkd.service >/dev/null 2>&1 || true
    ;;
    upgrade)
    ;;
    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
